version: 2.1

executors:
  java-8:
    working_directory: ~/build-working-directory
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          JAVA_OPTS: -XX:+UseG1GC
          # Disable Kotlin compiler daemon - https://discuss.kotlinlang.org/t/solved-disable-kotlin-compiler-process-keepalive/2622
          GRADLE_OPTS: -Dkotlin.compiler.execution.strategy="in-process"
  java-11:
    working_directory: ~/build-working-directory
    docker:
      - image: circleci/openjdk:11-jdk
        environment:
          # Disable Kotlin compiler daemon - https://discuss.kotlinlang.org/t/solved-disable-kotlin-compiler-process-keepalive/2622
          GRADLE_OPTS: -Dkotlin.compiler.execution.strategy="in-process"

commands:
  gradle-build:
    description: Runs './gradlew build' testing against the provided version
    steps:
      - run:
          name: Run Gradle Build
          command: ./gradlew build --scan
      - store_test_results:
          path: ~/build-working-directory/build/test-results/
  restore-home-cache:
    description: Restores the Gradle home cache.
    steps:
      - run:
          name: Generate cache key
          command: |
            mkdir -p build
            find settings.gradle.kts build.gradle.kts gradle buildSrc/src buildSrc/build.gradle.kts -type f -exec sha256sum '{}' \; | tee build/circle-ci-key.txt
      - restore_cache:
          keys:
            - v2-home-cache-{{ checksum "build/circle-ci-key.txt" }}
            - v2-home-cache-
  save-home-cache:
    description: Saves the Gradle home cache
    steps:
      - run:
          name: Generate cache key
          command: |
            mkdir -p build
            find settings.gradle.kts build.gradle.kts gradle buildSrc/src buildSrc/build.gradle.kts -type f -exec sha256sum '{}' \; | tee build/circle-ci-key.txt
      - save_cache:
          paths:
            - ~/.gradle
          key: v2-home-cache-{{ checksum "build/circle-ci-key.txt" }}
          when: always

#shared-steps:
#  generate-cache-key: &generate-cache-key
#    run:
#      command: |
#        mkdir -p build
#        find settings.gradle.kts build.gradle.kts gradle buildSrc/src buildSrc/build.gradle.kts -type f -exec sha256sum '{}' \; | tee build/circle-ci-key.txt
#      name: Generate cache key
#  restore-home-cache: &restore-home-cache
#    restore_cache:
#      keys:
#        - v2-home-cache-{{ checksum "build/circle-ci-key.txt" }}
#        - v2-home-cache-
#  save-home-cache: &save-home-cache
#    save_cache:
#      paths:
#        - ~/.gradle
#      key: v2-home-cache-{{ checksum "build/circle-ci-key.txt" }}
#      when: always
#  show-java-info: &show-java-info
#    run:
#      command: |
#        java -XshowSettings:vm -XX:+PrintCommandLineFlags -version
#        javac -version
#      name: Show Java Version
#  run-gradle-build: &run-gradle-build
#    run:
#      command: ./gradlew build --scan --stacktrace
#      name: Run Gradle Build
#  junit-platform-test-results: &junit-platform-test-results
#    store_test_results:
#      path: ~/build-working-directory/build/test-results/

jobs:
  test-java-8:
    executor: java-8
    steps:
      - checkout
      - restore-home-cache
      - gradle-build
      - save-home-cache
  test-java-11:
    executor: java-11
    steps:
      - checkout
      - restore-home-cache
      - gradle-build

workflows:
  version: 2
  build:
    jobs:
      - test-java-8
      - test-java-11:
          requires:
            - test-java-8
